#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 85
#define LARGE_STATE_COUNT 10
#define SYMBOL_COUNT 63
#define ALIAS_COUNT 2
#define TOKEN_COUNT 40
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 8

enum ts_symbol_identifiers {
  anon_sym_PIPE = 1,
  sym_any_character = 2,
  anon_sym_CARET = 3,
  sym_end_assertion = 4,
  sym_boundary_assertion = 5,
  sym_non_boundary_assertion = 6,
  anon_sym_LPAREN_QMARK = 7,
  anon_sym_EQ = 8,
  anon_sym_BANG = 9,
  anon_sym_RPAREN = 10,
  anon_sym_LPAREN_QMARK_LT = 11,
  sym_pattern_character = 12,
  anon_sym_LBRACK = 13,
  anon_sym_RBRACK = 14,
  anon_sym_LBRACK_COLON = 15,
  anon_sym_COLON_RBRACK = 16,
  sym_posix_class_name = 17,
  anon_sym_DASH = 18,
  anon_sym_BSLASH_DASH = 19,
  sym_class_character = 20,
  anon_sym_LPAREN = 21,
  anon_sym_GT = 22,
  anon_sym_LPAREN_QMARK_COLON = 23,
  anon_sym_STAR = 24,
  anon_sym_QMARK = 25,
  anon_sym_PLUS = 26,
  anon_sym_LBRACE = 27,
  anon_sym_COMMA = 28,
  anon_sym_RBRACE = 29,
  anon_sym_BSLASHk = 30,
  sym_decimal_escape = 31,
  aux_sym_character_class_escape_token1 = 32,
  aux_sym_character_class_escape_token2 = 33,
  sym_unicode_property = 34,
  sym_control_escape = 35,
  sym_control_letter_escape = 36,
  sym_identity_escape = 37,
  sym_group_name = 38,
  sym_decimal_digits = 39,
  sym_pattern = 40,
  sym_alternation = 41,
  sym_term = 42,
  sym_start_assertion = 43,
  sym_lookaround_assertion = 44,
  sym__lookahead_assertion = 45,
  sym__lookbehind_assertion = 46,
  sym_character_class = 47,
  sym_posix_character_class = 48,
  sym_class_range = 49,
  sym_anonymous_capturing_group = 50,
  sym_named_capturing_group = 51,
  sym_non_capturing_group = 52,
  sym_zero_or_more = 53,
  sym_one_or_more = 54,
  sym_optional = 55,
  sym_count_quantifier = 56,
  sym_backreference_escape = 57,
  sym_character_class_escape = 58,
  sym_unicode_property_value_expression = 59,
  aux_sym_alternation_repeat1 = 60,
  aux_sym_term_repeat1 = 61,
  aux_sym_character_class_repeat1 = 62,
  alias_sym_lazy = 63,
  alias_sym_unicode_property_name = 64,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_PIPE] = "|",
  [sym_any_character] = "any_character",
  [anon_sym_CARET] = "^",
  [sym_end_assertion] = "end_assertion",
  [sym_boundary_assertion] = "boundary_assertion",
  [sym_non_boundary_assertion] = "non_boundary_assertion",
  [anon_sym_LPAREN_QMARK] = "(\?",
  [anon_sym_EQ] = "=",
  [anon_sym_BANG] = "!",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LPAREN_QMARK_LT] = "(\?<",
  [sym_pattern_character] = "pattern_character",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACK_COLON] = "[:",
  [anon_sym_COLON_RBRACK] = ":]",
  [sym_posix_class_name] = "posix_class_name",
  [anon_sym_DASH] = "-",
  [anon_sym_BSLASH_DASH] = "identity_escape",
  [sym_class_character] = "class_character",
  [anon_sym_LPAREN] = "(",
  [anon_sym_GT] = ">",
  [anon_sym_LPAREN_QMARK_COLON] = "(\?:",
  [anon_sym_STAR] = "*",
  [anon_sym_QMARK] = "\?",
  [anon_sym_PLUS] = "+",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_BSLASHk] = "\\k",
  [sym_decimal_escape] = "decimal_escape",
  [aux_sym_character_class_escape_token1] = "character_class_escape_token1",
  [aux_sym_character_class_escape_token2] = "character_class_escape_token2",
  [sym_unicode_property] = "unicode_property_value",
  [sym_control_escape] = "control_escape",
  [sym_control_letter_escape] = "control_letter_escape",
  [sym_identity_escape] = "identity_escape",
  [sym_group_name] = "group_name",
  [sym_decimal_digits] = "decimal_digits",
  [sym_pattern] = "pattern",
  [sym_alternation] = "alternation",
  [sym_term] = "term",
  [sym_start_assertion] = "start_assertion",
  [sym_lookaround_assertion] = "lookaround_assertion",
  [sym__lookahead_assertion] = "_lookahead_assertion",
  [sym__lookbehind_assertion] = "_lookbehind_assertion",
  [sym_character_class] = "character_class",
  [sym_posix_character_class] = "posix_character_class",
  [sym_class_range] = "class_range",
  [sym_anonymous_capturing_group] = "anonymous_capturing_group",
  [sym_named_capturing_group] = "named_capturing_group",
  [sym_non_capturing_group] = "non_capturing_group",
  [sym_zero_or_more] = "zero_or_more",
  [sym_one_or_more] = "one_or_more",
  [sym_optional] = "optional",
  [sym_count_quantifier] = "count_quantifier",
  [sym_backreference_escape] = "backreference_escape",
  [sym_character_class_escape] = "character_class_escape",
  [sym_unicode_property_value_expression] = "unicode_property_value_expression",
  [aux_sym_alternation_repeat1] = "alternation_repeat1",
  [aux_sym_term_repeat1] = "term_repeat1",
  [aux_sym_character_class_repeat1] = "character_class_repeat1",
  [alias_sym_lazy] = "lazy",
  [alias_sym_unicode_property_name] = "unicode_property_name",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_any_character] = sym_any_character,
  [anon_sym_CARET] = anon_sym_CARET,
  [sym_end_assertion] = sym_end_assertion,
  [sym_boundary_assertion] = sym_boundary_assertion,
  [sym_non_boundary_assertion] = sym_non_boundary_assertion,
  [anon_sym_LPAREN_QMARK] = anon_sym_LPAREN_QMARK,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LPAREN_QMARK_LT] = anon_sym_LPAREN_QMARK_LT,
  [sym_pattern_character] = sym_pattern_character,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACK_COLON] = anon_sym_LBRACK_COLON,
  [anon_sym_COLON_RBRACK] = anon_sym_COLON_RBRACK,
  [sym_posix_class_name] = sym_posix_class_name,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_BSLASH_DASH] = sym_identity_escape,
  [sym_class_character] = sym_class_character,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LPAREN_QMARK_COLON] = anon_sym_LPAREN_QMARK_COLON,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_BSLASHk] = anon_sym_BSLASHk,
  [sym_decimal_escape] = sym_decimal_escape,
  [aux_sym_character_class_escape_token1] = aux_sym_character_class_escape_token1,
  [aux_sym_character_class_escape_token2] = aux_sym_character_class_escape_token2,
  [sym_unicode_property] = sym_unicode_property,
  [sym_control_escape] = sym_control_escape,
  [sym_control_letter_escape] = sym_control_letter_escape,
  [sym_identity_escape] = sym_identity_escape,
  [sym_group_name] = sym_group_name,
  [sym_decimal_digits] = sym_decimal_digits,
  [sym_pattern] = sym_pattern,
  [sym_alternation] = sym_alternation,
  [sym_term] = sym_term,
  [sym_start_assertion] = sym_start_assertion,
  [sym_lookaround_assertion] = sym_lookaround_assertion,
  [sym__lookahead_assertion] = sym__lookahead_assertion,
  [sym__lookbehind_assertion] = sym__lookbehind_assertion,
  [sym_character_class] = sym_character_class,
  [sym_posix_character_class] = sym_posix_character_class,
  [sym_class_range] = sym_class_range,
  [sym_anonymous_capturing_group] = sym_anonymous_capturing_group,
  [sym_named_capturing_group] = sym_named_capturing_group,
  [sym_non_capturing_group] = sym_non_capturing_group,
  [sym_zero_or_more] = sym_zero_or_more,
  [sym_one_or_more] = sym_one_or_more,
  [sym_optional] = sym_optional,
  [sym_count_quantifier] = sym_count_quantifier,
  [sym_backreference_escape] = sym_backreference_escape,
  [sym_character_class_escape] = sym_character_class_escape,
  [sym_unicode_property_value_expression] = sym_unicode_property_value_expression,
  [aux_sym_alternation_repeat1] = aux_sym_alternation_repeat1,
  [aux_sym_term_repeat1] = aux_sym_term_repeat1,
  [aux_sym_character_class_repeat1] = aux_sym_character_class_repeat1,
  [alias_sym_lazy] = alias_sym_lazy,
  [alias_sym_unicode_property_name] = alias_sym_unicode_property_name,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_any_character] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [sym_end_assertion] = {
    .visible = true,
    .named = true,
  },
  [sym_boundary_assertion] = {
    .visible = true,
    .named = true,
  },
  [sym_non_boundary_assertion] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN_QMARK_LT] = {
    .visible = true,
    .named = false,
  },
  [sym_pattern_character] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_posix_class_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_DASH] = {
    .visible = true,
    .named = true,
  },
  [sym_class_character] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN_QMARK_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHk] = {
    .visible = true,
    .named = false,
  },
  [sym_decimal_escape] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_character_class_escape_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_character_class_escape_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_unicode_property] = {
    .visible = true,
    .named = true,
  },
  [sym_control_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_control_letter_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_identity_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_group_name] = {
    .visible = true,
    .named = true,
  },
  [sym_decimal_digits] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_alternation] = {
    .visible = true,
    .named = true,
  },
  [sym_term] = {
    .visible = true,
    .named = true,
  },
  [sym_start_assertion] = {
    .visible = true,
    .named = true,
  },
  [sym_lookaround_assertion] = {
    .visible = true,
    .named = true,
  },
  [sym__lookahead_assertion] = {
    .visible = false,
    .named = true,
  },
  [sym__lookbehind_assertion] = {
    .visible = false,
    .named = true,
  },
  [sym_character_class] = {
    .visible = true,
    .named = true,
  },
  [sym_posix_character_class] = {
    .visible = true,
    .named = true,
  },
  [sym_class_range] = {
    .visible = true,
    .named = true,
  },
  [sym_anonymous_capturing_group] = {
    .visible = true,
    .named = true,
  },
  [sym_named_capturing_group] = {
    .visible = true,
    .named = true,
  },
  [sym_non_capturing_group] = {
    .visible = true,
    .named = true,
  },
  [sym_zero_or_more] = {
    .visible = true,
    .named = true,
  },
  [sym_one_or_more] = {
    .visible = true,
    .named = true,
  },
  [sym_optional] = {
    .visible = true,
    .named = true,
  },
  [sym_count_quantifier] = {
    .visible = true,
    .named = true,
  },
  [sym_backreference_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_character_class_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_unicode_property_value_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_alternation_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_term_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_character_class_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_lazy] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_unicode_property_name] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = sym_class_character,
  },
  [2] = {
    [1] = alias_sym_lazy,
  },
  [3] = {
    [0] = sym_class_character,
    [2] = sym_class_character,
  },
  [4] = {
    [2] = sym_class_character,
  },
  [5] = {
    [3] = alias_sym_lazy,
  },
  [6] = {
    [0] = alias_sym_unicode_property_name,
  },
  [7] = {
    [5] = alias_sym_lazy,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 12,
  [44] = 11,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 20,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 59,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 65,
  [81] = 72,
  [82] = 76,
  [83] = 83,
  [84] = 79,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(18);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '\r') SKIP(13);
      if (lookahead == '!') ADVANCE(27);
      if (lookahead == '$') ADVANCE(22);
      if (lookahead == '(') ADVANCE(43);
      if (lookahead == ')') ADVANCE(28);
      if (lookahead == '*') ADVANCE(46);
      if (lookahead == '+') ADVANCE(48);
      if (lookahead == ',') ADVANCE(50);
      if (lookahead == '-') ADVANCE(37);
      if (lookahead == '.') ADVANCE(20);
      if (lookahead == ':') ADVANCE(31);
      if (lookahead == '=') ADVANCE(26);
      if (lookahead == '>') ADVANCE(44);
      if (lookahead == '?') ADVANCE(47);
      if (lookahead == '[') ADVANCE(32);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead == ']') ADVANCE(33);
      if (lookahead == '^') ADVANCE(21);
      if (lookahead == '{') ADVANCE(49);
      if (lookahead == '|') ADVANCE(19);
      if (lookahead == '}') ADVANCE(51);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(40);
      if (lookahead == '\r') ADVANCE(39);
      if (lookahead == '-') ADVANCE(37);
      if (lookahead == '[') ADVANCE(42);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead == ']') ADVANCE(33);
      if (lookahead == '^') ADVANCE(21);
      if (lookahead != 0) ADVANCE(39);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == '\r') ADVANCE(39);
      if (lookahead == '-') ADVANCE(37);
      if (lookahead == '[') ADVANCE(42);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead == ']') ADVANCE(33);
      if (lookahead != 0) ADVANCE(39);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(4);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(4);
      if (lookahead == '\r') SKIP(3);
      if (lookahead == '!') ADVANCE(27);
      if (lookahead == ',') ADVANCE(50);
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == '=') ADVANCE(26);
      if (lookahead == '>') ADVANCE(44);
      if (lookahead == '}') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 5:
      if (lookahead == '\n') SKIP(6);
      END_STATE();
    case 6:
      if (lookahead == '\n') SKIP(6);
      if (lookahead == '\r') SKIP(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 7:
      if (lookahead == '\n') SKIP(8);
      END_STATE();
    case 8:
      if (lookahead == '\n') SKIP(8);
      if (lookahead == '\r') SKIP(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 9:
      ADVANCE_MAP(
        '-', 38,
        'B', 24,
        'b', 23,
        'c', 60,
        'k', 52,
        'P', 55,
        'p', 55,
        '0', 57,
        'f', 57,
        'n', 57,
        'r', 57,
        't', 57,
        'v', 57,
        'D', 54,
        'S', 54,
        'W', 54,
        'd', 54,
        's', 54,
        'w', 54,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(53);
      if (lookahead != 0) ADVANCE(59);
      END_STATE();
    case 10:
      ADVANCE_MAP(
        '-', 38,
        'c', 60,
        'P', 55,
        'p', 55,
        'D', 54,
        'S', 54,
        'W', 54,
        'd', 54,
        's', 54,
        'w', 54,
        '0', 57,
        'b', 57,
        'f', 57,
        'n', 57,
        'r', 57,
        't', 57,
        'v', 57,
      );
      if (lookahead != 0 &&
          (lookahead < '0' || '9' < lookahead) &&
          lookahead != 'k') ADVANCE(59);
      END_STATE();
    case 11:
      ADVANCE_MAP(
        'B', 24,
        'b', 23,
        'c', 60,
        'k', 52,
        'P', 55,
        'p', 55,
        '0', 57,
        'f', 57,
        'n', 57,
        'r', 57,
        't', 57,
        'v', 57,
        'D', 54,
        'S', 54,
        'W', 54,
        'd', 54,
        's', 54,
        'w', 54,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(53);
      if (lookahead != 0) ADVANCE(59);
      END_STATE();
    case 12:
      if (lookahead == ']') ADVANCE(35);
      END_STATE();
    case 13:
      if (eof) ADVANCE(18);
      if (lookahead == '\n') SKIP(0);
      END_STATE();
    case 14:
      if (eof) ADVANCE(18);
      if (lookahead == '\n') SKIP(15);
      END_STATE();
    case 15:
      if (eof) ADVANCE(18);
      if (lookahead == '\n') SKIP(15);
      if (lookahead == '\r') SKIP(14);
      if (lookahead == '$') ADVANCE(22);
      if (lookahead == '(') ADVANCE(43);
      if (lookahead == ')') ADVANCE(28);
      if (lookahead == '.') ADVANCE(20);
      if (lookahead == '?') ADVANCE(47);
      if (lookahead == '[') ADVANCE(32);
      if (lookahead == '\\') ADVANCE(11);
      if (lookahead == '^') ADVANCE(21);
      if (lookahead == '|') ADVANCE(19);
      if (lookahead != 0 &&
          (lookahead < '(' || '+' < lookahead) &&
          (lookahead < '[' || '^' < lookahead)) ADVANCE(30);
      END_STATE();
    case 16:
      if (eof) ADVANCE(18);
      if (lookahead == '\n') SKIP(17);
      END_STATE();
    case 17:
      if (eof) ADVANCE(18);
      if (lookahead == '\n') SKIP(17);
      if (lookahead == '\r') SKIP(16);
      if (lookahead == '$') ADVANCE(22);
      if (lookahead == '(') ADVANCE(43);
      if (lookahead == ')') ADVANCE(28);
      if (lookahead == '*') ADVANCE(46);
      if (lookahead == '+') ADVANCE(48);
      if (lookahead == '.') ADVANCE(20);
      if (lookahead == '?') ADVANCE(47);
      if (lookahead == '[') ADVANCE(32);
      if (lookahead == '\\') ADVANCE(11);
      if (lookahead == '^') ADVANCE(21);
      if (lookahead == '{') ADVANCE(49);
      if (lookahead == '|') ADVANCE(19);
      if (lookahead != 0 &&
          (lookahead < '[' || '^' < lookahead)) ADVANCE(30);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_any_character);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_end_assertion);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_boundary_assertion);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_non_boundary_assertion);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LPAREN_QMARK);
      if (lookahead == ':') ADVANCE(45);
      if (lookahead == '<') ADVANCE(29);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LPAREN_QMARK_LT);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_pattern_character);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_pattern_character);
      if (lookahead == ']') ADVANCE(35);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead == ':') ADVANCE(34);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LBRACK_COLON);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_COLON_RBRACK);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_posix_class_name);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_BSLASH_DASH);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_class_character);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_class_character);
      if (lookahead == '\n') ADVANCE(40);
      if (lookahead == '\r') ADVANCE(39);
      if (lookahead == '[') ADVANCE(42);
      if (lookahead == '^') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '-' &&
          (lookahead < '[' || '^' < lookahead)) ADVANCE(39);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_class_character);
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == '\r') ADVANCE(39);
      if (lookahead == '[') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '-' &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(39);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_class_character);
      if (lookahead == ':') ADVANCE(34);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead == '?') ADVANCE(25);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LPAREN_QMARK_COLON);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_BSLASHk);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_decimal_escape);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_character_class_escape_token1);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_character_class_escape_token2);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_unicode_property);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_control_escape);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_control_letter_escape);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identity_escape);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identity_escape);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_group_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_decimal_digits);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 15},
  [2] = {.lex_state = 15},
  [3] = {.lex_state = 15},
  [4] = {.lex_state = 15},
  [5] = {.lex_state = 15},
  [6] = {.lex_state = 15},
  [7] = {.lex_state = 15},
  [8] = {.lex_state = 15},
  [9] = {.lex_state = 15},
  [10] = {.lex_state = 17},
  [11] = {.lex_state = 17},
  [12] = {.lex_state = 17},
  [13] = {.lex_state = 17},
  [14] = {.lex_state = 17},
  [15] = {.lex_state = 17},
  [16] = {.lex_state = 17},
  [17] = {.lex_state = 17},
  [18] = {.lex_state = 17},
  [19] = {.lex_state = 17},
  [20] = {.lex_state = 17},
  [21] = {.lex_state = 17},
  [22] = {.lex_state = 17},
  [23] = {.lex_state = 17},
  [24] = {.lex_state = 17},
  [25] = {.lex_state = 15},
  [26] = {.lex_state = 15},
  [27] = {.lex_state = 15},
  [28] = {.lex_state = 15},
  [29] = {.lex_state = 15},
  [30] = {.lex_state = 15},
  [31] = {.lex_state = 15},
  [32] = {.lex_state = 15},
  [33] = {.lex_state = 15},
  [34] = {.lex_state = 15},
  [35] = {.lex_state = 15},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 4},
  [58] = {.lex_state = 4},
  [59] = {.lex_state = 6},
  [60] = {.lex_state = 6},
  [61] = {.lex_state = 4},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 4},
  [64] = {.lex_state = 8},
  [65] = {.lex_state = 4},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 8},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 4},
  [72] = {.lex_state = 4},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 6},
  [75] = {.lex_state = 4},
  [76] = {.lex_state = 8},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 4},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 4},
  [81] = {.lex_state = 4},
  [82] = {.lex_state = 8},
  [83] = {.lex_state = 4},
  [84] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_any_character] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [sym_end_assertion] = ACTIONS(1),
    [sym_boundary_assertion] = ACTIONS(1),
    [sym_non_boundary_assertion] = ACTIONS(1),
    [anon_sym_LPAREN_QMARK] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LPAREN_QMARK_LT] = ACTIONS(1),
    [sym_pattern_character] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACK_COLON] = ACTIONS(1),
    [anon_sym_COLON_RBRACK] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_BSLASH_DASH] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LPAREN_QMARK_COLON] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_BSLASHk] = ACTIONS(1),
    [sym_decimal_escape] = ACTIONS(1),
    [aux_sym_character_class_escape_token1] = ACTIONS(1),
    [aux_sym_character_class_escape_token2] = ACTIONS(1),
    [sym_control_escape] = ACTIONS(1),
    [sym_control_letter_escape] = ACTIONS(1),
    [sym_identity_escape] = ACTIONS(1),
  },
  [1] = {
    [sym_pattern] = STATE(77),
    [sym_alternation] = STATE(62),
    [sym_term] = STATE(53),
    [sym_start_assertion] = STATE(10),
    [sym_lookaround_assertion] = STATE(10),
    [sym__lookahead_assertion] = STATE(24),
    [sym__lookbehind_assertion] = STATE(24),
    [sym_character_class] = STATE(10),
    [sym_posix_character_class] = STATE(10),
    [sym_anonymous_capturing_group] = STATE(10),
    [sym_named_capturing_group] = STATE(10),
    [sym_non_capturing_group] = STATE(10),
    [sym_backreference_escape] = STATE(10),
    [sym_character_class_escape] = STATE(10),
    [aux_sym_alternation_repeat1] = STATE(52),
    [aux_sym_term_repeat1] = STATE(9),
    [anon_sym_PIPE] = ACTIONS(3),
    [sym_any_character] = ACTIONS(5),
    [anon_sym_CARET] = ACTIONS(7),
    [sym_end_assertion] = ACTIONS(5),
    [sym_boundary_assertion] = ACTIONS(5),
    [sym_non_boundary_assertion] = ACTIONS(5),
    [anon_sym_LPAREN_QMARK] = ACTIONS(9),
    [anon_sym_LPAREN_QMARK_LT] = ACTIONS(11),
    [sym_pattern_character] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACK_COLON] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LPAREN_QMARK_COLON] = ACTIONS(19),
    [anon_sym_BSLASHk] = ACTIONS(21),
    [sym_decimal_escape] = ACTIONS(5),
    [aux_sym_character_class_escape_token1] = ACTIONS(23),
    [aux_sym_character_class_escape_token2] = ACTIONS(25),
    [sym_control_escape] = ACTIONS(27),
    [sym_control_letter_escape] = ACTIONS(5),
    [sym_identity_escape] = ACTIONS(27),
  },
  [2] = {
    [sym_pattern] = STATE(66),
    [sym_alternation] = STATE(62),
    [sym_term] = STATE(53),
    [sym_start_assertion] = STATE(10),
    [sym_lookaround_assertion] = STATE(10),
    [sym__lookahead_assertion] = STATE(24),
    [sym__lookbehind_assertion] = STATE(24),
    [sym_character_class] = STATE(10),
    [sym_posix_character_class] = STATE(10),
    [sym_anonymous_capturing_group] = STATE(10),
    [sym_named_capturing_group] = STATE(10),
    [sym_non_capturing_group] = STATE(10),
    [sym_backreference_escape] = STATE(10),
    [sym_character_class_escape] = STATE(10),
    [aux_sym_alternation_repeat1] = STATE(52),
    [aux_sym_term_repeat1] = STATE(9),
    [anon_sym_PIPE] = ACTIONS(3),
    [sym_any_character] = ACTIONS(5),
    [anon_sym_CARET] = ACTIONS(7),
    [sym_end_assertion] = ACTIONS(5),
    [sym_boundary_assertion] = ACTIONS(5),
    [sym_non_boundary_assertion] = ACTIONS(5),
    [anon_sym_LPAREN_QMARK] = ACTIONS(9),
    [anon_sym_LPAREN_QMARK_LT] = ACTIONS(11),
    [sym_pattern_character] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACK_COLON] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LPAREN_QMARK_COLON] = ACTIONS(19),
    [anon_sym_BSLASHk] = ACTIONS(21),
    [sym_decimal_escape] = ACTIONS(5),
    [aux_sym_character_class_escape_token1] = ACTIONS(23),
    [aux_sym_character_class_escape_token2] = ACTIONS(25),
    [sym_control_escape] = ACTIONS(27),
    [sym_control_letter_escape] = ACTIONS(5),
    [sym_identity_escape] = ACTIONS(27),
  },
  [3] = {
    [sym_pattern] = STATE(67),
    [sym_alternation] = STATE(62),
    [sym_term] = STATE(53),
    [sym_start_assertion] = STATE(10),
    [sym_lookaround_assertion] = STATE(10),
    [sym__lookahead_assertion] = STATE(24),
    [sym__lookbehind_assertion] = STATE(24),
    [sym_character_class] = STATE(10),
    [sym_posix_character_class] = STATE(10),
    [sym_anonymous_capturing_group] = STATE(10),
    [sym_named_capturing_group] = STATE(10),
    [sym_non_capturing_group] = STATE(10),
    [sym_backreference_escape] = STATE(10),
    [sym_character_class_escape] = STATE(10),
    [aux_sym_alternation_repeat1] = STATE(52),
    [aux_sym_term_repeat1] = STATE(9),
    [anon_sym_PIPE] = ACTIONS(3),
    [sym_any_character] = ACTIONS(5),
    [anon_sym_CARET] = ACTIONS(7),
    [sym_end_assertion] = ACTIONS(5),
    [sym_boundary_assertion] = ACTIONS(5),
    [sym_non_boundary_assertion] = ACTIONS(5),
    [anon_sym_LPAREN_QMARK] = ACTIONS(9),
    [anon_sym_LPAREN_QMARK_LT] = ACTIONS(11),
    [sym_pattern_character] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACK_COLON] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LPAREN_QMARK_COLON] = ACTIONS(19),
    [anon_sym_BSLASHk] = ACTIONS(21),
    [sym_decimal_escape] = ACTIONS(5),
    [aux_sym_character_class_escape_token1] = ACTIONS(23),
    [aux_sym_character_class_escape_token2] = ACTIONS(25),
    [sym_control_escape] = ACTIONS(27),
    [sym_control_letter_escape] = ACTIONS(5),
    [sym_identity_escape] = ACTIONS(27),
  },
  [4] = {
    [sym_pattern] = STATE(70),
    [sym_alternation] = STATE(62),
    [sym_term] = STATE(53),
    [sym_start_assertion] = STATE(10),
    [sym_lookaround_assertion] = STATE(10),
    [sym__lookahead_assertion] = STATE(24),
    [sym__lookbehind_assertion] = STATE(24),
    [sym_character_class] = STATE(10),
    [sym_posix_character_class] = STATE(10),
    [sym_anonymous_capturing_group] = STATE(10),
    [sym_named_capturing_group] = STATE(10),
    [sym_non_capturing_group] = STATE(10),
    [sym_backreference_escape] = STATE(10),
    [sym_character_class_escape] = STATE(10),
    [aux_sym_alternation_repeat1] = STATE(52),
    [aux_sym_term_repeat1] = STATE(9),
    [anon_sym_PIPE] = ACTIONS(3),
    [sym_any_character] = ACTIONS(5),
    [anon_sym_CARET] = ACTIONS(7),
    [sym_end_assertion] = ACTIONS(5),
    [sym_boundary_assertion] = ACTIONS(5),
    [sym_non_boundary_assertion] = ACTIONS(5),
    [anon_sym_LPAREN_QMARK] = ACTIONS(9),
    [anon_sym_LPAREN_QMARK_LT] = ACTIONS(11),
    [sym_pattern_character] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACK_COLON] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LPAREN_QMARK_COLON] = ACTIONS(19),
    [anon_sym_BSLASHk] = ACTIONS(21),
    [sym_decimal_escape] = ACTIONS(5),
    [aux_sym_character_class_escape_token1] = ACTIONS(23),
    [aux_sym_character_class_escape_token2] = ACTIONS(25),
    [sym_control_escape] = ACTIONS(27),
    [sym_control_letter_escape] = ACTIONS(5),
    [sym_identity_escape] = ACTIONS(27),
  },
  [5] = {
    [sym_pattern] = STATE(73),
    [sym_alternation] = STATE(62),
    [sym_term] = STATE(53),
    [sym_start_assertion] = STATE(10),
    [sym_lookaround_assertion] = STATE(10),
    [sym__lookahead_assertion] = STATE(24),
    [sym__lookbehind_assertion] = STATE(24),
    [sym_character_class] = STATE(10),
    [sym_posix_character_class] = STATE(10),
    [sym_anonymous_capturing_group] = STATE(10),
    [sym_named_capturing_group] = STATE(10),
    [sym_non_capturing_group] = STATE(10),
    [sym_backreference_escape] = STATE(10),
    [sym_character_class_escape] = STATE(10),
    [aux_sym_alternation_repeat1] = STATE(52),
    [aux_sym_term_repeat1] = STATE(9),
    [anon_sym_PIPE] = ACTIONS(3),
    [sym_any_character] = ACTIONS(5),
    [anon_sym_CARET] = ACTIONS(7),
    [sym_end_assertion] = ACTIONS(5),
    [sym_boundary_assertion] = ACTIONS(5),
    [sym_non_boundary_assertion] = ACTIONS(5),
    [anon_sym_LPAREN_QMARK] = ACTIONS(9),
    [anon_sym_LPAREN_QMARK_LT] = ACTIONS(11),
    [sym_pattern_character] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACK_COLON] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LPAREN_QMARK_COLON] = ACTIONS(19),
    [anon_sym_BSLASHk] = ACTIONS(21),
    [sym_decimal_escape] = ACTIONS(5),
    [aux_sym_character_class_escape_token1] = ACTIONS(23),
    [aux_sym_character_class_escape_token2] = ACTIONS(25),
    [sym_control_escape] = ACTIONS(27),
    [sym_control_letter_escape] = ACTIONS(5),
    [sym_identity_escape] = ACTIONS(27),
  },
  [6] = {
    [sym_pattern] = STATE(68),
    [sym_alternation] = STATE(62),
    [sym_term] = STATE(53),
    [sym_start_assertion] = STATE(10),
    [sym_lookaround_assertion] = STATE(10),
    [sym__lookahead_assertion] = STATE(24),
    [sym__lookbehind_assertion] = STATE(24),
    [sym_character_class] = STATE(10),
    [sym_posix_character_class] = STATE(10),
    [sym_anonymous_capturing_group] = STATE(10),
    [sym_named_capturing_group] = STATE(10),
    [sym_non_capturing_group] = STATE(10),
    [sym_backreference_escape] = STATE(10),
    [sym_character_class_escape] = STATE(10),
    [aux_sym_alternation_repeat1] = STATE(52),
    [aux_sym_term_repeat1] = STATE(9),
    [anon_sym_PIPE] = ACTIONS(3),
    [sym_any_character] = ACTIONS(5),
    [anon_sym_CARET] = ACTIONS(7),
    [sym_end_assertion] = ACTIONS(5),
    [sym_boundary_assertion] = ACTIONS(5),
    [sym_non_boundary_assertion] = ACTIONS(5),
    [anon_sym_LPAREN_QMARK] = ACTIONS(9),
    [anon_sym_LPAREN_QMARK_LT] = ACTIONS(11),
    [sym_pattern_character] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACK_COLON] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LPAREN_QMARK_COLON] = ACTIONS(19),
    [anon_sym_BSLASHk] = ACTIONS(21),
    [sym_decimal_escape] = ACTIONS(5),
    [aux_sym_character_class_escape_token1] = ACTIONS(23),
    [aux_sym_character_class_escape_token2] = ACTIONS(25),
    [sym_control_escape] = ACTIONS(27),
    [sym_control_letter_escape] = ACTIONS(5),
    [sym_identity_escape] = ACTIONS(27),
  },
  [7] = {
    [sym_term] = STATE(56),
    [sym_start_assertion] = STATE(10),
    [sym_lookaround_assertion] = STATE(10),
    [sym__lookahead_assertion] = STATE(24),
    [sym__lookbehind_assertion] = STATE(24),
    [sym_character_class] = STATE(10),
    [sym_posix_character_class] = STATE(10),
    [sym_anonymous_capturing_group] = STATE(10),
    [sym_named_capturing_group] = STATE(10),
    [sym_non_capturing_group] = STATE(10),
    [sym_backreference_escape] = STATE(10),
    [sym_character_class_escape] = STATE(10),
    [aux_sym_term_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(29),
    [anon_sym_PIPE] = ACTIONS(29),
    [sym_any_character] = ACTIONS(5),
    [anon_sym_CARET] = ACTIONS(7),
    [sym_end_assertion] = ACTIONS(5),
    [sym_boundary_assertion] = ACTIONS(5),
    [sym_non_boundary_assertion] = ACTIONS(5),
    [anon_sym_LPAREN_QMARK] = ACTIONS(9),
    [anon_sym_RPAREN] = ACTIONS(29),
    [anon_sym_LPAREN_QMARK_LT] = ACTIONS(11),
    [sym_pattern_character] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACK_COLON] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LPAREN_QMARK_COLON] = ACTIONS(19),
    [anon_sym_BSLASHk] = ACTIONS(21),
    [sym_decimal_escape] = ACTIONS(5),
    [aux_sym_character_class_escape_token1] = ACTIONS(23),
    [aux_sym_character_class_escape_token2] = ACTIONS(25),
    [sym_control_escape] = ACTIONS(27),
    [sym_control_letter_escape] = ACTIONS(5),
    [sym_identity_escape] = ACTIONS(27),
  },
  [8] = {
    [sym_start_assertion] = STATE(10),
    [sym_lookaround_assertion] = STATE(10),
    [sym__lookahead_assertion] = STATE(24),
    [sym__lookbehind_assertion] = STATE(24),
    [sym_character_class] = STATE(10),
    [sym_posix_character_class] = STATE(10),
    [sym_anonymous_capturing_group] = STATE(10),
    [sym_named_capturing_group] = STATE(10),
    [sym_non_capturing_group] = STATE(10),
    [sym_backreference_escape] = STATE(10),
    [sym_character_class_escape] = STATE(10),
    [aux_sym_term_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(31),
    [anon_sym_PIPE] = ACTIONS(31),
    [sym_any_character] = ACTIONS(33),
    [anon_sym_CARET] = ACTIONS(36),
    [sym_end_assertion] = ACTIONS(33),
    [sym_boundary_assertion] = ACTIONS(33),
    [sym_non_boundary_assertion] = ACTIONS(33),
    [anon_sym_LPAREN_QMARK] = ACTIONS(39),
    [anon_sym_RPAREN] = ACTIONS(31),
    [anon_sym_LPAREN_QMARK_LT] = ACTIONS(42),
    [sym_pattern_character] = ACTIONS(33),
    [anon_sym_LBRACK] = ACTIONS(45),
    [anon_sym_LBRACK_COLON] = ACTIONS(48),
    [anon_sym_LPAREN] = ACTIONS(51),
    [anon_sym_LPAREN_QMARK_COLON] = ACTIONS(54),
    [anon_sym_BSLASHk] = ACTIONS(57),
    [sym_decimal_escape] = ACTIONS(33),
    [aux_sym_character_class_escape_token1] = ACTIONS(60),
    [aux_sym_character_class_escape_token2] = ACTIONS(63),
    [sym_control_escape] = ACTIONS(66),
    [sym_control_letter_escape] = ACTIONS(33),
    [sym_identity_escape] = ACTIONS(66),
  },
  [9] = {
    [sym_start_assertion] = STATE(10),
    [sym_lookaround_assertion] = STATE(10),
    [sym__lookahead_assertion] = STATE(24),
    [sym__lookbehind_assertion] = STATE(24),
    [sym_character_class] = STATE(10),
    [sym_posix_character_class] = STATE(10),
    [sym_anonymous_capturing_group] = STATE(10),
    [sym_named_capturing_group] = STATE(10),
    [sym_non_capturing_group] = STATE(10),
    [sym_backreference_escape] = STATE(10),
    [sym_character_class_escape] = STATE(10),
    [aux_sym_term_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(69),
    [anon_sym_PIPE] = ACTIONS(69),
    [sym_any_character] = ACTIONS(5),
    [anon_sym_CARET] = ACTIONS(7),
    [sym_end_assertion] = ACTIONS(5),
    [sym_boundary_assertion] = ACTIONS(5),
    [sym_non_boundary_assertion] = ACTIONS(5),
    [anon_sym_LPAREN_QMARK] = ACTIONS(9),
    [anon_sym_RPAREN] = ACTIONS(69),
    [anon_sym_LPAREN_QMARK_LT] = ACTIONS(11),
    [sym_pattern_character] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACK_COLON] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LPAREN_QMARK_COLON] = ACTIONS(19),
    [anon_sym_BSLASHk] = ACTIONS(21),
    [sym_decimal_escape] = ACTIONS(5),
    [aux_sym_character_class_escape_token1] = ACTIONS(23),
    [aux_sym_character_class_escape_token2] = ACTIONS(25),
    [sym_control_escape] = ACTIONS(27),
    [sym_control_letter_escape] = ACTIONS(5),
    [sym_identity_escape] = ACTIONS(27),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(75), 1,
      anon_sym_STAR,
    ACTIONS(77), 1,
      anon_sym_QMARK,
    ACTIONS(79), 1,
      anon_sym_PLUS,
    ACTIONS(81), 1,
      anon_sym_LBRACE,
    STATE(30), 4,
      sym_zero_or_more,
      sym_one_or_more,
      sym_optional,
      sym_count_quantifier,
    ACTIONS(73), 6,
      anon_sym_LPAREN_QMARK,
      sym_pattern_character,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym_control_escape,
      sym_identity_escape,
    ACTIONS(71), 16,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_any_character,
      anon_sym_CARET,
      sym_end_assertion,
      sym_boundary_assertion,
      sym_non_boundary_assertion,
      anon_sym_RPAREN,
      anon_sym_LPAREN_QMARK_LT,
      anon_sym_LBRACK_COLON,
      anon_sym_LPAREN_QMARK_COLON,
      anon_sym_BSLASHk,
      sym_decimal_escape,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_letter_escape,
  [45] = 2,
    ACTIONS(85), 6,
      anon_sym_LPAREN_QMARK,
      sym_pattern_character,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym_control_escape,
      sym_identity_escape,
    ACTIONS(83), 20,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_any_character,
      anon_sym_CARET,
      sym_end_assertion,
      sym_boundary_assertion,
      sym_non_boundary_assertion,
      anon_sym_RPAREN,
      anon_sym_LPAREN_QMARK_LT,
      anon_sym_LBRACK_COLON,
      anon_sym_LPAREN_QMARK_COLON,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_PLUS,
      anon_sym_LBRACE,
      anon_sym_BSLASHk,
      sym_decimal_escape,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_letter_escape,
  [76] = 2,
    ACTIONS(89), 6,
      anon_sym_LPAREN_QMARK,
      sym_pattern_character,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym_control_escape,
      sym_identity_escape,
    ACTIONS(87), 20,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_any_character,
      anon_sym_CARET,
      sym_end_assertion,
      sym_boundary_assertion,
      sym_non_boundary_assertion,
      anon_sym_RPAREN,
      anon_sym_LPAREN_QMARK_LT,
      anon_sym_LBRACK_COLON,
      anon_sym_LPAREN_QMARK_COLON,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_PLUS,
      anon_sym_LBRACE,
      anon_sym_BSLASHk,
      sym_decimal_escape,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_letter_escape,
  [107] = 2,
    ACTIONS(93), 6,
      anon_sym_LPAREN_QMARK,
      sym_pattern_character,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym_control_escape,
      sym_identity_escape,
    ACTIONS(91), 20,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_any_character,
      anon_sym_CARET,
      sym_end_assertion,
      sym_boundary_assertion,
      sym_non_boundary_assertion,
      anon_sym_RPAREN,
      anon_sym_LPAREN_QMARK_LT,
      anon_sym_LBRACK_COLON,
      anon_sym_LPAREN_QMARK_COLON,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_PLUS,
      anon_sym_LBRACE,
      anon_sym_BSLASHk,
      sym_decimal_escape,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_letter_escape,
  [138] = 2,
    ACTIONS(97), 6,
      anon_sym_LPAREN_QMARK,
      sym_pattern_character,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym_control_escape,
      sym_identity_escape,
    ACTIONS(95), 20,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_any_character,
      anon_sym_CARET,
      sym_end_assertion,
      sym_boundary_assertion,
      sym_non_boundary_assertion,
      anon_sym_RPAREN,
      anon_sym_LPAREN_QMARK_LT,
      anon_sym_LBRACK_COLON,
      anon_sym_LPAREN_QMARK_COLON,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_PLUS,
      anon_sym_LBRACE,
      anon_sym_BSLASHk,
      sym_decimal_escape,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_letter_escape,
  [169] = 2,
    ACTIONS(101), 6,
      anon_sym_LPAREN_QMARK,
      sym_pattern_character,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym_control_escape,
      sym_identity_escape,
    ACTIONS(99), 20,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_any_character,
      anon_sym_CARET,
      sym_end_assertion,
      sym_boundary_assertion,
      sym_non_boundary_assertion,
      anon_sym_RPAREN,
      anon_sym_LPAREN_QMARK_LT,
      anon_sym_LBRACK_COLON,
      anon_sym_LPAREN_QMARK_COLON,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_PLUS,
      anon_sym_LBRACE,
      anon_sym_BSLASHk,
      sym_decimal_escape,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_letter_escape,
  [200] = 2,
    ACTIONS(105), 6,
      anon_sym_LPAREN_QMARK,
      sym_pattern_character,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym_control_escape,
      sym_identity_escape,
    ACTIONS(103), 20,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_any_character,
      anon_sym_CARET,
      sym_end_assertion,
      sym_boundary_assertion,
      sym_non_boundary_assertion,
      anon_sym_RPAREN,
      anon_sym_LPAREN_QMARK_LT,
      anon_sym_LBRACK_COLON,
      anon_sym_LPAREN_QMARK_COLON,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_PLUS,
      anon_sym_LBRACE,
      anon_sym_BSLASHk,
      sym_decimal_escape,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_letter_escape,
  [231] = 2,
    ACTIONS(109), 6,
      anon_sym_LPAREN_QMARK,
      sym_pattern_character,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym_control_escape,
      sym_identity_escape,
    ACTIONS(107), 20,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_any_character,
      anon_sym_CARET,
      sym_end_assertion,
      sym_boundary_assertion,
      sym_non_boundary_assertion,
      anon_sym_RPAREN,
      anon_sym_LPAREN_QMARK_LT,
      anon_sym_LBRACK_COLON,
      anon_sym_LPAREN_QMARK_COLON,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_PLUS,
      anon_sym_LBRACE,
      anon_sym_BSLASHk,
      sym_decimal_escape,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_letter_escape,
  [262] = 2,
    ACTIONS(113), 6,
      anon_sym_LPAREN_QMARK,
      sym_pattern_character,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym_control_escape,
      sym_identity_escape,
    ACTIONS(111), 20,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_any_character,
      anon_sym_CARET,
      sym_end_assertion,
      sym_boundary_assertion,
      sym_non_boundary_assertion,
      anon_sym_RPAREN,
      anon_sym_LPAREN_QMARK_LT,
      anon_sym_LBRACK_COLON,
      anon_sym_LPAREN_QMARK_COLON,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_PLUS,
      anon_sym_LBRACE,
      anon_sym_BSLASHk,
      sym_decimal_escape,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_letter_escape,
  [293] = 2,
    ACTIONS(117), 6,
      anon_sym_LPAREN_QMARK,
      sym_pattern_character,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym_control_escape,
      sym_identity_escape,
    ACTIONS(115), 20,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_any_character,
      anon_sym_CARET,
      sym_end_assertion,
      sym_boundary_assertion,
      sym_non_boundary_assertion,
      anon_sym_RPAREN,
      anon_sym_LPAREN_QMARK_LT,
      anon_sym_LBRACK_COLON,
      anon_sym_LPAREN_QMARK_COLON,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_PLUS,
      anon_sym_LBRACE,
      anon_sym_BSLASHk,
      sym_decimal_escape,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_letter_escape,
  [324] = 2,
    ACTIONS(121), 6,
      anon_sym_LPAREN_QMARK,
      sym_pattern_character,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym_control_escape,
      sym_identity_escape,
    ACTIONS(119), 20,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_any_character,
      anon_sym_CARET,
      sym_end_assertion,
      sym_boundary_assertion,
      sym_non_boundary_assertion,
      anon_sym_RPAREN,
      anon_sym_LPAREN_QMARK_LT,
      anon_sym_LBRACK_COLON,
      anon_sym_LPAREN_QMARK_COLON,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_PLUS,
      anon_sym_LBRACE,
      anon_sym_BSLASHk,
      sym_decimal_escape,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_letter_escape,
  [355] = 2,
    ACTIONS(125), 6,
      anon_sym_LPAREN_QMARK,
      sym_pattern_character,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym_control_escape,
      sym_identity_escape,
    ACTIONS(123), 20,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_any_character,
      anon_sym_CARET,
      sym_end_assertion,
      sym_boundary_assertion,
      sym_non_boundary_assertion,
      anon_sym_RPAREN,
      anon_sym_LPAREN_QMARK_LT,
      anon_sym_LBRACK_COLON,
      anon_sym_LPAREN_QMARK_COLON,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_PLUS,
      anon_sym_LBRACE,
      anon_sym_BSLASHk,
      sym_decimal_escape,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_letter_escape,
  [386] = 2,
    ACTIONS(129), 6,
      anon_sym_LPAREN_QMARK,
      sym_pattern_character,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym_control_escape,
      sym_identity_escape,
    ACTIONS(127), 20,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_any_character,
      anon_sym_CARET,
      sym_end_assertion,
      sym_boundary_assertion,
      sym_non_boundary_assertion,
      anon_sym_RPAREN,
      anon_sym_LPAREN_QMARK_LT,
      anon_sym_LBRACK_COLON,
      anon_sym_LPAREN_QMARK_COLON,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_PLUS,
      anon_sym_LBRACE,
      anon_sym_BSLASHk,
      sym_decimal_escape,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_letter_escape,
  [417] = 2,
    ACTIONS(133), 6,
      anon_sym_LPAREN_QMARK,
      sym_pattern_character,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym_control_escape,
      sym_identity_escape,
    ACTIONS(131), 20,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_any_character,
      anon_sym_CARET,
      sym_end_assertion,
      sym_boundary_assertion,
      sym_non_boundary_assertion,
      anon_sym_RPAREN,
      anon_sym_LPAREN_QMARK_LT,
      anon_sym_LBRACK_COLON,
      anon_sym_LPAREN_QMARK_COLON,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_PLUS,
      anon_sym_LBRACE,
      anon_sym_BSLASHk,
      sym_decimal_escape,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_letter_escape,
  [448] = 2,
    ACTIONS(137), 6,
      anon_sym_LPAREN_QMARK,
      sym_pattern_character,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym_control_escape,
      sym_identity_escape,
    ACTIONS(135), 20,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_any_character,
      anon_sym_CARET,
      sym_end_assertion,
      sym_boundary_assertion,
      sym_non_boundary_assertion,
      anon_sym_RPAREN,
      anon_sym_LPAREN_QMARK_LT,
      anon_sym_LBRACK_COLON,
      anon_sym_LPAREN_QMARK_COLON,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_PLUS,
      anon_sym_LBRACE,
      anon_sym_BSLASHk,
      sym_decimal_escape,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_letter_escape,
  [479] = 3,
    ACTIONS(143), 1,
      anon_sym_QMARK,
    ACTIONS(141), 5,
      anon_sym_LPAREN_QMARK,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym_control_escape,
      sym_identity_escape,
    ACTIONS(139), 17,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_any_character,
      anon_sym_CARET,
      sym_end_assertion,
      sym_boundary_assertion,
      sym_non_boundary_assertion,
      anon_sym_RPAREN,
      anon_sym_LPAREN_QMARK_LT,
      sym_pattern_character,
      anon_sym_LBRACK_COLON,
      anon_sym_LPAREN_QMARK_COLON,
      anon_sym_BSLASHk,
      sym_decimal_escape,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_letter_escape,
  [509] = 3,
    ACTIONS(149), 1,
      anon_sym_QMARK,
    ACTIONS(147), 5,
      anon_sym_LPAREN_QMARK,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym_control_escape,
      sym_identity_escape,
    ACTIONS(145), 17,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_any_character,
      anon_sym_CARET,
      sym_end_assertion,
      sym_boundary_assertion,
      sym_non_boundary_assertion,
      anon_sym_RPAREN,
      anon_sym_LPAREN_QMARK_LT,
      sym_pattern_character,
      anon_sym_LBRACK_COLON,
      anon_sym_LPAREN_QMARK_COLON,
      anon_sym_BSLASHk,
      sym_decimal_escape,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_letter_escape,
  [539] = 3,
    ACTIONS(155), 1,
      anon_sym_QMARK,
    ACTIONS(153), 5,
      anon_sym_LPAREN_QMARK,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym_control_escape,
      sym_identity_escape,
    ACTIONS(151), 17,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_any_character,
      anon_sym_CARET,
      sym_end_assertion,
      sym_boundary_assertion,
      sym_non_boundary_assertion,
      anon_sym_RPAREN,
      anon_sym_LPAREN_QMARK_LT,
      sym_pattern_character,
      anon_sym_LBRACK_COLON,
      anon_sym_LPAREN_QMARK_COLON,
      anon_sym_BSLASHk,
      sym_decimal_escape,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_letter_escape,
  [569] = 3,
    ACTIONS(161), 1,
      anon_sym_QMARK,
    ACTIONS(159), 5,
      anon_sym_LPAREN_QMARK,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym_control_escape,
      sym_identity_escape,
    ACTIONS(157), 17,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_any_character,
      anon_sym_CARET,
      sym_end_assertion,
      sym_boundary_assertion,
      sym_non_boundary_assertion,
      anon_sym_RPAREN,
      anon_sym_LPAREN_QMARK_LT,
      sym_pattern_character,
      anon_sym_LBRACK_COLON,
      anon_sym_LPAREN_QMARK_COLON,
      anon_sym_BSLASHk,
      sym_decimal_escape,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_letter_escape,
  [599] = 3,
    ACTIONS(167), 1,
      anon_sym_QMARK,
    ACTIONS(165), 5,
      anon_sym_LPAREN_QMARK,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym_control_escape,
      sym_identity_escape,
    ACTIONS(163), 17,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_any_character,
      anon_sym_CARET,
      sym_end_assertion,
      sym_boundary_assertion,
      sym_non_boundary_assertion,
      anon_sym_RPAREN,
      anon_sym_LPAREN_QMARK_LT,
      sym_pattern_character,
      anon_sym_LBRACK_COLON,
      anon_sym_LPAREN_QMARK_COLON,
      anon_sym_BSLASHk,
      sym_decimal_escape,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_letter_escape,
  [629] = 2,
    ACTIONS(169), 5,
      anon_sym_LPAREN_QMARK,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym_control_escape,
      sym_identity_escape,
    ACTIONS(31), 17,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_any_character,
      anon_sym_CARET,
      sym_end_assertion,
      sym_boundary_assertion,
      sym_non_boundary_assertion,
      anon_sym_RPAREN,
      anon_sym_LPAREN_QMARK_LT,
      sym_pattern_character,
      anon_sym_LBRACK_COLON,
      anon_sym_LPAREN_QMARK_COLON,
      anon_sym_BSLASHk,
      sym_decimal_escape,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_letter_escape,
  [656] = 2,
    ACTIONS(173), 5,
      anon_sym_LPAREN_QMARK,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym_control_escape,
      sym_identity_escape,
    ACTIONS(171), 17,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_any_character,
      anon_sym_CARET,
      sym_end_assertion,
      sym_boundary_assertion,
      sym_non_boundary_assertion,
      anon_sym_RPAREN,
      anon_sym_LPAREN_QMARK_LT,
      sym_pattern_character,
      anon_sym_LBRACK_COLON,
      anon_sym_LPAREN_QMARK_COLON,
      anon_sym_BSLASHk,
      sym_decimal_escape,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_letter_escape,
  [683] = 2,
    ACTIONS(177), 5,
      anon_sym_LPAREN_QMARK,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym_control_escape,
      sym_identity_escape,
    ACTIONS(175), 17,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_any_character,
      anon_sym_CARET,
      sym_end_assertion,
      sym_boundary_assertion,
      sym_non_boundary_assertion,
      anon_sym_RPAREN,
      anon_sym_LPAREN_QMARK_LT,
      sym_pattern_character,
      anon_sym_LBRACK_COLON,
      anon_sym_LPAREN_QMARK_COLON,
      anon_sym_BSLASHk,
      sym_decimal_escape,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_letter_escape,
  [710] = 2,
    ACTIONS(181), 5,
      anon_sym_LPAREN_QMARK,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym_control_escape,
      sym_identity_escape,
    ACTIONS(179), 17,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_any_character,
      anon_sym_CARET,
      sym_end_assertion,
      sym_boundary_assertion,
      sym_non_boundary_assertion,
      anon_sym_RPAREN,
      anon_sym_LPAREN_QMARK_LT,
      sym_pattern_character,
      anon_sym_LBRACK_COLON,
      anon_sym_LPAREN_QMARK_COLON,
      anon_sym_BSLASHk,
      sym_decimal_escape,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_letter_escape,
  [737] = 2,
    ACTIONS(185), 5,
      anon_sym_LPAREN_QMARK,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym_control_escape,
      sym_identity_escape,
    ACTIONS(183), 17,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_any_character,
      anon_sym_CARET,
      sym_end_assertion,
      sym_boundary_assertion,
      sym_non_boundary_assertion,
      anon_sym_RPAREN,
      anon_sym_LPAREN_QMARK_LT,
      sym_pattern_character,
      anon_sym_LBRACK_COLON,
      anon_sym_LPAREN_QMARK_COLON,
      anon_sym_BSLASHk,
      sym_decimal_escape,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_letter_escape,
  [764] = 2,
    ACTIONS(189), 5,
      anon_sym_LPAREN_QMARK,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym_control_escape,
      sym_identity_escape,
    ACTIONS(187), 17,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_any_character,
      anon_sym_CARET,
      sym_end_assertion,
      sym_boundary_assertion,
      sym_non_boundary_assertion,
      anon_sym_RPAREN,
      anon_sym_LPAREN_QMARK_LT,
      sym_pattern_character,
      anon_sym_LBRACK_COLON,
      anon_sym_LPAREN_QMARK_COLON,
      anon_sym_BSLASHk,
      sym_decimal_escape,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_letter_escape,
  [791] = 9,
    ACTIONS(191), 1,
      anon_sym_CARET,
    ACTIONS(193), 1,
      anon_sym_RBRACK,
    ACTIONS(195), 1,
      anon_sym_LBRACK_COLON,
    ACTIONS(197), 1,
      anon_sym_DASH,
    ACTIONS(201), 1,
      aux_sym_character_class_escape_token1,
    ACTIONS(203), 1,
      aux_sym_character_class_escape_token2,
    STATE(37), 2,
      sym_class_range,
      aux_sym_character_class_repeat1,
    STATE(48), 2,
      sym_posix_character_class,
      sym_character_class_escape,
    ACTIONS(199), 5,
      anon_sym_BSLASH_DASH,
      sym_class_character,
      sym_control_escape,
      sym_control_letter_escape,
      sym_identity_escape,
  [825] = 8,
    ACTIONS(195), 1,
      anon_sym_LBRACK_COLON,
    ACTIONS(197), 1,
      anon_sym_DASH,
    ACTIONS(201), 1,
      aux_sym_character_class_escape_token1,
    ACTIONS(203), 1,
      aux_sym_character_class_escape_token2,
    ACTIONS(205), 1,
      anon_sym_RBRACK,
    STATE(40), 2,
      sym_class_range,
      aux_sym_character_class_repeat1,
    STATE(48), 2,
      sym_posix_character_class,
      sym_character_class_escape,
    ACTIONS(199), 5,
      anon_sym_BSLASH_DASH,
      sym_class_character,
      sym_control_escape,
      sym_control_letter_escape,
      sym_identity_escape,
  [856] = 8,
    ACTIONS(195), 1,
      anon_sym_LBRACK_COLON,
    ACTIONS(197), 1,
      anon_sym_DASH,
    ACTIONS(201), 1,
      aux_sym_character_class_escape_token1,
    ACTIONS(203), 1,
      aux_sym_character_class_escape_token2,
    ACTIONS(205), 1,
      anon_sym_RBRACK,
    STATE(39), 2,
      sym_class_range,
      aux_sym_character_class_repeat1,
    STATE(48), 2,
      sym_posix_character_class,
      sym_character_class_escape,
    ACTIONS(199), 5,
      anon_sym_BSLASH_DASH,
      sym_class_character,
      sym_control_escape,
      sym_control_letter_escape,
      sym_identity_escape,
  [887] = 8,
    ACTIONS(195), 1,
      anon_sym_LBRACK_COLON,
    ACTIONS(197), 1,
      anon_sym_DASH,
    ACTIONS(201), 1,
      aux_sym_character_class_escape_token1,
    ACTIONS(203), 1,
      aux_sym_character_class_escape_token2,
    ACTIONS(207), 1,
      anon_sym_RBRACK,
    STATE(40), 2,
      sym_class_range,
      aux_sym_character_class_repeat1,
    STATE(48), 2,
      sym_posix_character_class,
      sym_character_class_escape,
    ACTIONS(199), 5,
      anon_sym_BSLASH_DASH,
      sym_class_character,
      sym_control_escape,
      sym_control_letter_escape,
      sym_identity_escape,
  [918] = 8,
    ACTIONS(209), 1,
      anon_sym_RBRACK,
    ACTIONS(211), 1,
      anon_sym_LBRACK_COLON,
    ACTIONS(214), 1,
      anon_sym_DASH,
    ACTIONS(220), 1,
      aux_sym_character_class_escape_token1,
    ACTIONS(223), 1,
      aux_sym_character_class_escape_token2,
    STATE(40), 2,
      sym_class_range,
      aux_sym_character_class_repeat1,
    STATE(48), 2,
      sym_posix_character_class,
      sym_character_class_escape,
    ACTIONS(217), 5,
      anon_sym_BSLASH_DASH,
      sym_class_character,
      sym_control_escape,
      sym_control_letter_escape,
      sym_identity_escape,
  [949] = 6,
    ACTIONS(195), 1,
      anon_sym_LBRACK_COLON,
    ACTIONS(201), 1,
      aux_sym_character_class_escape_token1,
    ACTIONS(203), 1,
      aux_sym_character_class_escape_token2,
    ACTIONS(226), 1,
      anon_sym_DASH,
    STATE(50), 2,
      sym_posix_character_class,
      sym_character_class_escape,
    ACTIONS(228), 5,
      anon_sym_BSLASH_DASH,
      sym_class_character,
      sym_control_escape,
      sym_control_letter_escape,
      sym_identity_escape,
  [973] = 6,
    ACTIONS(195), 1,
      anon_sym_LBRACK_COLON,
    ACTIONS(201), 1,
      aux_sym_character_class_escape_token1,
    ACTIONS(203), 1,
      aux_sym_character_class_escape_token2,
    ACTIONS(230), 1,
      anon_sym_DASH,
    STATE(49), 2,
      sym_posix_character_class,
      sym_character_class_escape,
    ACTIONS(232), 5,
      anon_sym_BSLASH_DASH,
      sym_class_character,
      sym_control_escape,
      sym_control_letter_escape,
      sym_identity_escape,
  [997] = 1,
    ACTIONS(89), 10,
      anon_sym_RBRACK,
      anon_sym_LBRACK_COLON,
      anon_sym_DASH,
      anon_sym_BSLASH_DASH,
      sym_class_character,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_escape,
      sym_control_letter_escape,
      sym_identity_escape,
  [1010] = 1,
    ACTIONS(85), 10,
      anon_sym_RBRACK,
      anon_sym_LBRACK_COLON,
      anon_sym_DASH,
      anon_sym_BSLASH_DASH,
      sym_class_character,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_escape,
      sym_control_letter_escape,
      sym_identity_escape,
  [1023] = 1,
    ACTIONS(234), 10,
      anon_sym_RBRACK,
      anon_sym_LBRACK_COLON,
      anon_sym_DASH,
      anon_sym_BSLASH_DASH,
      sym_class_character,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_escape,
      sym_control_letter_escape,
      sym_identity_escape,
  [1036] = 1,
    ACTIONS(236), 10,
      anon_sym_RBRACK,
      anon_sym_LBRACK_COLON,
      anon_sym_DASH,
      anon_sym_BSLASH_DASH,
      sym_class_character,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_escape,
      sym_control_letter_escape,
      sym_identity_escape,
  [1049] = 2,
    ACTIONS(240), 1,
      anon_sym_DASH,
    ACTIONS(238), 9,
      anon_sym_RBRACK,
      anon_sym_LBRACK_COLON,
      anon_sym_BSLASH_DASH,
      sym_class_character,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_escape,
      sym_control_letter_escape,
      sym_identity_escape,
  [1064] = 2,
    ACTIONS(245), 1,
      anon_sym_DASH,
    ACTIONS(243), 9,
      anon_sym_RBRACK,
      anon_sym_LBRACK_COLON,
      anon_sym_BSLASH_DASH,
      sym_class_character,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_escape,
      sym_control_letter_escape,
      sym_identity_escape,
  [1079] = 1,
    ACTIONS(248), 10,
      anon_sym_RBRACK,
      anon_sym_LBRACK_COLON,
      anon_sym_DASH,
      anon_sym_BSLASH_DASH,
      sym_class_character,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_escape,
      sym_control_letter_escape,
      sym_identity_escape,
  [1092] = 1,
    ACTIONS(250), 10,
      anon_sym_RBRACK,
      anon_sym_LBRACK_COLON,
      anon_sym_DASH,
      anon_sym_BSLASH_DASH,
      sym_class_character,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_escape,
      sym_control_letter_escape,
      sym_identity_escape,
  [1105] = 1,
    ACTIONS(121), 10,
      anon_sym_RBRACK,
      anon_sym_LBRACK_COLON,
      anon_sym_DASH,
      anon_sym_BSLASH_DASH,
      sym_class_character,
      aux_sym_character_class_escape_token1,
      aux_sym_character_class_escape_token2,
      sym_control_escape,
      sym_control_letter_escape,
      sym_identity_escape,
  [1118] = 3,
    ACTIONS(3), 1,
      anon_sym_PIPE,
    STATE(55), 1,
      aux_sym_alternation_repeat1,
    ACTIONS(252), 2,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
  [1129] = 3,
    ACTIONS(3), 1,
      anon_sym_PIPE,
    STATE(54), 1,
      aux_sym_alternation_repeat1,
    ACTIONS(254), 2,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
  [1140] = 3,
    ACTIONS(3), 1,
      anon_sym_PIPE,
    STATE(55), 1,
      aux_sym_alternation_repeat1,
    ACTIONS(256), 2,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
  [1151] = 3,
    ACTIONS(260), 1,
      anon_sym_PIPE,
    STATE(55), 1,
      aux_sym_alternation_repeat1,
    ACTIONS(258), 2,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
  [1162] = 1,
    ACTIONS(258), 3,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [1168] = 2,
    ACTIONS(265), 1,
      sym_group_name,
    ACTIONS(263), 2,
      anon_sym_EQ,
      anon_sym_BANG,
  [1176] = 2,
    ACTIONS(267), 1,
      anon_sym_COMMA,
    ACTIONS(269), 1,
      anon_sym_RBRACE,
  [1183] = 2,
    ACTIONS(271), 1,
      sym_unicode_property,
    STATE(72), 1,
      sym_unicode_property_value_expression,
  [1190] = 2,
    ACTIONS(271), 1,
      sym_unicode_property,
    STATE(81), 1,
      sym_unicode_property_value_expression,
  [1197] = 2,
    ACTIONS(273), 1,
      anon_sym_EQ,
    ACTIONS(275), 1,
      anon_sym_RBRACE,
  [1204] = 1,
    ACTIONS(254), 2,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
  [1209] = 1,
    ACTIONS(277), 2,
      anon_sym_EQ,
      anon_sym_BANG,
  [1214] = 1,
    ACTIONS(279), 1,
      sym_decimal_digits,
  [1218] = 1,
    ACTIONS(281), 1,
      anon_sym_COLON_RBRACK,
  [1222] = 1,
    ACTIONS(283), 1,
      anon_sym_RPAREN,
  [1226] = 1,
    ACTIONS(285), 1,
      anon_sym_RPAREN,
  [1230] = 1,
    ACTIONS(287), 1,
      anon_sym_RPAREN,
  [1234] = 1,
    ACTIONS(289), 1,
      sym_decimal_digits,
  [1238] = 1,
    ACTIONS(291), 1,
      anon_sym_RPAREN,
  [1242] = 1,
    ACTIONS(293), 1,
      anon_sym_GT,
  [1246] = 1,
    ACTIONS(295), 1,
      anon_sym_RBRACE,
  [1250] = 1,
    ACTIONS(297), 1,
      anon_sym_RPAREN,
  [1254] = 1,
    ACTIONS(299), 1,
      sym_unicode_property,
  [1258] = 1,
    ACTIONS(301), 1,
      sym_group_name,
  [1262] = 1,
    ACTIONS(303), 1,
      sym_posix_class_name,
  [1266] = 1,
    ACTIONS(305), 1,
      ts_builtin_sym_end,
  [1270] = 1,
    ACTIONS(307), 1,
      anon_sym_RBRACE,
  [1274] = 1,
    ACTIONS(309), 1,
      anon_sym_LBRACE,
  [1278] = 1,
    ACTIONS(311), 1,
      anon_sym_COLON_RBRACK,
  [1282] = 1,
    ACTIONS(313), 1,
      anon_sym_RBRACE,
  [1286] = 1,
    ACTIONS(315), 1,
      sym_posix_class_name,
  [1290] = 1,
    ACTIONS(317), 1,
      anon_sym_RBRACE,
  [1294] = 1,
    ACTIONS(319), 1,
      anon_sym_LBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(10)] = 0,
  [SMALL_STATE(11)] = 45,
  [SMALL_STATE(12)] = 76,
  [SMALL_STATE(13)] = 107,
  [SMALL_STATE(14)] = 138,
  [SMALL_STATE(15)] = 169,
  [SMALL_STATE(16)] = 200,
  [SMALL_STATE(17)] = 231,
  [SMALL_STATE(18)] = 262,
  [SMALL_STATE(19)] = 293,
  [SMALL_STATE(20)] = 324,
  [SMALL_STATE(21)] = 355,
  [SMALL_STATE(22)] = 386,
  [SMALL_STATE(23)] = 417,
  [SMALL_STATE(24)] = 448,
  [SMALL_STATE(25)] = 479,
  [SMALL_STATE(26)] = 509,
  [SMALL_STATE(27)] = 539,
  [SMALL_STATE(28)] = 569,
  [SMALL_STATE(29)] = 599,
  [SMALL_STATE(30)] = 629,
  [SMALL_STATE(31)] = 656,
  [SMALL_STATE(32)] = 683,
  [SMALL_STATE(33)] = 710,
  [SMALL_STATE(34)] = 737,
  [SMALL_STATE(35)] = 764,
  [SMALL_STATE(36)] = 791,
  [SMALL_STATE(37)] = 825,
  [SMALL_STATE(38)] = 856,
  [SMALL_STATE(39)] = 887,
  [SMALL_STATE(40)] = 918,
  [SMALL_STATE(41)] = 949,
  [SMALL_STATE(42)] = 973,
  [SMALL_STATE(43)] = 997,
  [SMALL_STATE(44)] = 1010,
  [SMALL_STATE(45)] = 1023,
  [SMALL_STATE(46)] = 1036,
  [SMALL_STATE(47)] = 1049,
  [SMALL_STATE(48)] = 1064,
  [SMALL_STATE(49)] = 1079,
  [SMALL_STATE(50)] = 1092,
  [SMALL_STATE(51)] = 1105,
  [SMALL_STATE(52)] = 1118,
  [SMALL_STATE(53)] = 1129,
  [SMALL_STATE(54)] = 1140,
  [SMALL_STATE(55)] = 1151,
  [SMALL_STATE(56)] = 1162,
  [SMALL_STATE(57)] = 1168,
  [SMALL_STATE(58)] = 1176,
  [SMALL_STATE(59)] = 1183,
  [SMALL_STATE(60)] = 1190,
  [SMALL_STATE(61)] = 1197,
  [SMALL_STATE(62)] = 1204,
  [SMALL_STATE(63)] = 1209,
  [SMALL_STATE(64)] = 1214,
  [SMALL_STATE(65)] = 1218,
  [SMALL_STATE(66)] = 1222,
  [SMALL_STATE(67)] = 1226,
  [SMALL_STATE(68)] = 1230,
  [SMALL_STATE(69)] = 1234,
  [SMALL_STATE(70)] = 1238,
  [SMALL_STATE(71)] = 1242,
  [SMALL_STATE(72)] = 1246,
  [SMALL_STATE(73)] = 1250,
  [SMALL_STATE(74)] = 1254,
  [SMALL_STATE(75)] = 1258,
  [SMALL_STATE(76)] = 1262,
  [SMALL_STATE(77)] = 1266,
  [SMALL_STATE(78)] = 1270,
  [SMALL_STATE(79)] = 1274,
  [SMALL_STATE(80)] = 1278,
  [SMALL_STATE(81)] = 1282,
  [SMALL_STATE(82)] = 1286,
  [SMALL_STATE(83)] = 1290,
  [SMALL_STATE(84)] = 1294,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_alternation_repeat1, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_term_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_term_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_term_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_term_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_term_repeat1, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_character_class_escape, 4, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character_class_escape, 4, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_character_class_escape, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character_class_escape, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_assertion, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_assertion, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_backreference_escape, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_backreference_escape, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_character_class, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character_class, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_character_class, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character_class, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_capturing_group, 5, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_named_capturing_group, 5, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__lookbehind_assertion, 4, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__lookbehind_assertion, 4, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_character_class, 4, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character_class, 4, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_posix_character_class, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_posix_character_class, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonymous_capturing_group, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_anonymous_capturing_group, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_non_capturing_group, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_non_capturing_group, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__lookahead_assertion, 4, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__lookahead_assertion, 4, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lookaround_assertion, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lookaround_assertion, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_zero_or_more, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_zero_or_more, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_optional, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_optional, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_one_or_more, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_one_or_more, 1, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_count_quantifier, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_count_quantifier, 3, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_count_quantifier, 5, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_count_quantifier, 5, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_term_repeat1, 2, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_one_or_more, 2, 0, 2),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_one_or_more, 2, 0, 2),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_zero_or_more, 2, 0, 2),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_zero_or_more, 2, 0, 2),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_optional, 2, 0, 2),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_optional, 2, 0, 2),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_count_quantifier, 4, 0, 5),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_count_quantifier, 4, 0, 5),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_count_quantifier, 6, 0, 7),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_count_quantifier, 6, 0, 7),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [195] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [197] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_character_class_repeat1, 2, 0, 0),
  [211] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_character_class_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [214] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_character_class_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [217] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_character_class_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [220] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_character_class_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [223] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_character_class_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [226] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [228] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [230] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [232] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [234] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class_range, 3, 0, 4),
  [236] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class_range, 3, 0, 3),
  [238] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_character_class_repeat1, 1, 0, 1),
  [240] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_character_class_repeat1, 1, 0, 1), SHIFT(42),
  [243] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_character_class_repeat1, 1, 0, 0),
  [245] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_character_class_repeat1, 1, 0, 0), SHIFT(41),
  [248] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class_range, 3, 0, 1),
  [250] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class_range, 3, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alternation, 1, 0, 0),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 1, 0, 0),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alternation, 2, 0, 0),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_alternation_repeat1, 2, 0, 0),
  [260] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_alternation_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unicode_property_value_expression, 1, 0, 0),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [305] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unicode_property_value_expression, 3, 0, 6),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_regex(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
